name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Ruby (2.7)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: Setup Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        
    - name: Build and test with RSpec and Cucumber
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        exec rake db:create db:migrate
        bundle exec rspec
        bundle exec cucumber
        
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
